language: ruby
rvm:
  - 2.5.3

addons:
  postgresql: 9.6

before_install:
  - "bundle install"

before_script:
  - cp config/database.yml.travis config/database.yml

script:
  - bin/rake db:create db:migrate RAILS_ENV=test
  - bin/rake
  - bundle exec rubocop app config spec
  - brakeman --exit-on-warn --quiet -f plain

services:
  - redis-server
