language: ruby
rvm:
  - 2.5.3

addons:
  postgresql: 9.6

before_install:
  - "bundle install"
  - "gem install rubocop"

before_script:
  - cp config/database.yml.travis config/database.yml

script:
  - bin/rake db:create db:migrate RAILS_ENV=test
  - bin/rake
  - rubocop app config spec

services:
  - redis-server
