version: "3"

volumes:
  db-data:
    external: false
  redis-data:
    external: false

services:
  db:
    environment:
      POSTGRES_USER: ${VEIN_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${VEIN_DATABASE_PASSWORD}
    image: postgres@sha256:d4729fad66e863ffc6100716ee4e4479045086a98feca58a732c7624dad86ecd
    volumes:
      - db-data:/user/local/pgsql/data
  redis:
    image: redis@sha256:b22a5030704efa865bf03fdc4f5828d969f0edd1be9c159f0e9dc2f33be31f5b
    command: redis-server
    volumes:
      - redis-data:/data

  web:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env
    tty: true
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - redis
      - db
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
